'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import { MathJax } from 'better-react-mathjax';
import { useCanvasResize } from '@/hooks/useCanvasResize';
import { CoreIdeasAndFeatures } from '@/components/CoreIdeasAndFeatures/CoreIdeasAndFeatures';
import styles from './world-models.module.css';

/* ====================================================================
   Data
   ==================================================================== */

const coreIdeas = [
  {
    title: 'Vision-Memory-Controller (V-M-C)',
    desc: 'Decompose the agent into V (VAE compresses frames to z), M (MDN-RNN predicts dynamics), and C (tiny linear controller)',
    detail: "Inspired by how our brains work, the agent is split into three modules: V (Vision) is a Variational Autoencoder that compresses each 64\u00d764 frame into a small latent vector z of 32 dimensions (CarRacing) or 64 dimensions (VizDoom). M (Memory) is an MDN-RNN \u2014 an LSTM with 256 hidden units whose output parameterizes a Mixture Density Network with 5 Gaussian components. It predicts the probability distribution over the next latent state given the current state, action, and hidden memory. C (Controller) is deliberately kept tiny: a single linear mapping from [z_t; h_t] to actions, giving only 867 parameters for CarRacing. This separation means V and M can be trained with standard unsupervised learning, while only C needs to be optimized for the task reward.",
  },
  {
    title: 'Dream Training',
    desc: 'Train the controller entirely in hallucinated environments generated by V+M \u2014 no real environment interaction during policy optimization',
    detail: 'The key insight is that once V and M are trained on real experience, the controller C can be trained entirely inside the \u201cdream\u201d of M. In dream mode, V is removed \u2014 the MDN-RNN generates latent z vectors directly, and C maps them to actions that feed back into M. This creates a closed loop (M \u2192 C \u2192 M) that simulates an entire environment in latent space. The temperature parameter \u03c4 controls sampling stochasticity: \u03c4 = 1.0 matches the real distribution, while \u03c4 > 1.0 makes dreams more unpredictable and challenging. Training with \u03c4 > 1 can produce controllers that are more robust in the real environment because they have learned to handle worst-case scenarios. This dream training runs orders of magnitude faster than real environment interaction.',
  },
  {
    title: 'CMA-ES Optimization',
    desc: "Evolve the controller's 867 parameters using Covariance Matrix Adaptation Evolution Strategy \u2014 no gradient-based RL for the policy",
    detail: "Rather than using policy gradient methods (REINFORCE, PPO, etc.), the controller is optimized using CMA-ES (Covariance Matrix Adaptation Evolution Strategy). CMA-ES maintains a multivariate Gaussian distribution over the 867-dimensional parameter space of C. Each generation: (1) sample a population of parameter vectors, (2) evaluate each by running the controller in dreams and measuring cumulative reward, (3) update the mean and covariance matrix based on the fitness ranking. This works because: the controller is so small (867 params) that evolution is tractable, CMA-ES handles non-differentiable objectives naturally, and it can be parallelized across many dream rollouts. The authors used a population size of 64 with 16 workers.",
  },
];

const keyFeatures = [
  { title: 'Tiny Controller', desc: 'Only 867 parameters in the controller, optimized by evolution not gradients' },
  { title: 'Dream Training', desc: 'Learn policies in hallucinated environments at ~100x the speed of real interaction' },
  { title: 'Modular Design', desc: 'V, M, C trained independently, enabling mix-and-match and modular upgrades' },
];

const componentInfo: Record<string, { title: string; desc: string }> = {
  obs: {
    title: 'Image Observation',
    desc: 'Raw 64\u00d764\u00d73 RGB frames from the environment (CarRacing or VizDoom). These high-dimensional observations are compressed by V into compact latent representations. In dream mode, no images are generated \u2014 the entire simulation happens in the latent space.',
  },
  vmodel: {
    title: 'V Model (Variational Autoencoder)',
    desc: 'A convolutional VAE with 4 conv layers (stride 2) in the encoder and 4 deconv layers in the decoder. Compresses 64\u00d764\u00d73 images into a latent vector z ~ N(\u03bc, \u03c3). For CarRacing, z is 32-dim; for VizDoom, 64-dim. Trained independently on collected frames using the standard VAE loss (reconstruction + KL). The encoder is used during real-time play; the decoder is only needed for visualization.',
  },
  mmodel: {
    title: 'M Model (MDN-RNN)',
    desc: "An LSTM with 256 hidden units whose output feeds into a Mixture Density Network with K=5 Gaussian components. Given (z_t, a_t, h_t), it outputs (\u03c0_i, \u03bc_i, \u03c3_i) for i=1..K, defining P(z_{t+1}). During training, the loss is the negative log-likelihood of the actual next z. The hidden state h_t serves as the agent's compressed memory of the episode history. Also predicts P(done) to know when episodes end in dreams.",
  },
  cmodel: {
    title: 'C Model (Linear Controller)',
    desc: 'The simplest possible policy: a_t = W_c [z_t; h_t] + b_c. For CarRacing: z is 32-dim, h is 256-dim, action is 3-dim (steering, gas, brake), giving (32+256)\u00d73 + 3 = 867 parameters. This extreme simplicity is deliberate \u2014 it forces all the intelligence into V and M, and makes the controller small enough for evolutionary optimization. The controller maps the combined latent state and memory to continuous actions.',
  },
  mmodel_dream: {
    title: 'M as Dream Environment',
    desc: 'In dream mode, M replaces the real environment entirely. It receives actions from C and generates the next latent state by sampling from its MDN output. The temperature \u03c4 scales the standard deviations: \u03c3\u2032 = \u03c4 \u00d7 \u03c3. At \u03c4=1.0, dreams match the training distribution. At \u03c4>1.0, dreams become more stochastic and challenging, which can lead to more robust controllers.',
  },
  cmodel_dream: {
    title: 'C in Dream Training',
    desc: 'During dream training, the controller receives z_t and h_t from M (not from real observations) and outputs actions that feed back into M. Multiple dream rollouts are run in parallel to evaluate each candidate controller. CMA-ES uses the cumulative rewards from these dream rollouts as fitness scores to evolve the controller parameters.',
  },
  dreamenv: {
    title: 'Hallucinated Environment',
    desc: 'The closed loop between M and C constitutes a complete hallucinated environment. V is not needed \u2014 everything happens in the compact latent space. This makes dream rollouts extremely fast compared to real environment steps. The agent can practice thousands of episodes in dreams before being tested in reality.',
  },
  population: {
    title: 'Population of Controllers',
    desc: 'CMA-ES maintains a population of controller parameter vectors sampled from a multivariate Gaussian N(\u03bc, \u03a3). Each generation, 64 candidate controllers are sampled, each defined by a different W_c and b_c. The population explores the 867-dimensional parameter space guided by the covariance matrix.',
  },
  evaluate: {
    title: 'Evaluation in Dreams',
    desc: 'Each candidate controller is evaluated by running it inside the dream environment (the M model) for multiple episodes. The cumulative reward across episodes serves as the fitness score. This evaluation is fast because dreams run entirely in latent space without image rendering.',
  },
  evolve: {
    title: 'Evolution and Selection',
    desc: 'After evaluation, CMA-ES ranks the candidates by fitness, updates the mean \u03bc toward the best performers, and adapts the covariance matrix \u03a3 to focus search around promising regions. Over generations, the distribution concentrates on high-performing controller parameters.',
  },
};

interface BenchmarkTask {
  data: Record<string, number>;
  note: string;
  maxVal: number;
}

const benchmarkData: Record<string, BenchmarkTask> = {
  carracing: {
    data: {
      'World Models': 906,
      'Gym Leader': 838,
      'A3C (cont)': 591,
      'A3C (disc)': 652,
      DQN: 343,
    },
    note: 'World Models achieves 906 on CarRacing-v0, surpassing all prior methods including the human gym leader (838).',
    maxVal: 1000,
  },
  vizdoom: {
    data: {
      'World Models': 1100,
      'World Models (dream)': 1060,
      'Baseline RNN': 850,
      Random: 210,
    },
    note: 'VizDoom Take Cover: World Models survives ~1100 timesteps on average, and dream-trained variants achieve competitive ~1060 steps.',
    maxVal: 1200,
  },
};

const methodColors: Record<string, string> = {
  'World Models': '#a855f7',
  'World Models (dream)': '#7c3aed',
  'Gym Leader': '#f59e0b',
  'A3C (cont)': '#3b82f6',
  'A3C (disc)': '#10b981',
  DQN: '#888',
  'Baseline RNN': '#3b82f6',
  Random: '#666',
};

/* ====================================================================
   Canvas helpers (pure functions, no DOM)
   ==================================================================== */

function seededRandom(seed: number) {
  let s = seed;
  return function () {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    return s / 0x7fffffff;
  };
}

function generateLatentGrid(
  timestep: number,
  temperature: number,
  rows: number,
  cols: number,
): number[][] {
  const grid: number[][] = [];
  const rng = seededRandom(42 + timestep * 7);
  const prevRng = seededRandom(42 + (timestep - 1) * 7);

  for (let r = 0; r < rows; r++) {
    const row: number[] = [];
    for (let c = 0; c < cols; c++) {
      const baseVal = rng();
      const prevVal = prevRng();
      const noise = (rng() - 0.5) * temperature;
      const smoothing = Math.max(0.05, 1.0 - temperature * 0.4);
      const val = Math.max(
        0,
        Math.min(1, prevVal * smoothing + baseVal * (1 - smoothing) + noise * 0.3),
      );
      row.push(val);
    }
    grid.push(row);
  }
  return grid;
}

function latentColor(val: number): string {
  const r = Math.round(val * val * 255);
  const g = Math.round(val * 200 + 55);
  const b = Math.round((1 - val) * 220 + 35);
  return `rgb(${r}, ${g}, ${b})`;
}

/* ====================================================================
   Component
   ==================================================================== */

export default function WorldModelsPage() {
  /* ---- Interactive state ---- */
  const [activeComponent, setActiveComponent] = useState<string | null>(null);
  const [activeModelItem, setActiveModelItem] = useState<string | null>(null);
  const [temperature, setTemperature] = useState(10); // slider value 1-20, display = value/10
  const [selectedTask, setSelectedTask] = useState('carracing');

  /* ---- Derived values ---- */
  const tau = temperature / 10;
  const avgVariance = (tau * 0.12).toFixed(2);
  const stability = tau <= 0.5 ? 'High' : tau <= 1.2 ? 'Med' : 'Low';
  const stabilityColor =
    stability === 'High' ? '#10b981' : stability === 'Med' ? '#f59e0b' : '#ef4444';

  /* ---- Canvas refs ---- */
  const dreamCanvasRef = useRef<HTMLCanvasElement | null>(null);
  const dreamSize = useCanvasResize(dreamCanvasRef);

  /* ---- Dream rollout drawing ---- */
  const drawDreamRollout = useCallback(() => {
    const canvas = dreamCanvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const w = dreamSize.width;
    const h = dreamSize.height;
    if (w === 0 || h === 0) return;

    const totalSteps = 20;
    const gridRows = 4;
    const gridCols = 8;
    const numMixtureComponents = 5;

    const pad = { left: 15, right: 15, top: 30, bottom: 70 };
    const availW = w - pad.left - pad.right;

    ctx.clearRect(0, 0, w, h);

    // Title
    ctx.fillStyle = '#888';
    ctx.font = '10px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('MDN-RNN Latent Rollout (z values over 20 timesteps)', w / 2, 15);

    // Timestep grids
    const cellW = Math.min(20, availW / totalSteps - 3);
    const cellH = Math.min(10, (h - pad.top - pad.bottom) / (gridRows + 4));
    const stepSpacing = availW / totalSteps;

    for (let t = 0; t < totalSteps; t++) {
      const grid = generateLatentGrid(t, tau, gridRows, gridCols);
      const sx = pad.left + t * stepSpacing;
      const sy = pad.top;

      ctx.fillStyle = 'rgba(0,0,0,0.3)';
      ctx.fillRect(sx, sy, cellW, cellH * gridRows);

      const cw = cellW / gridCols;
      const ch = cellH;
      for (let r = 0; r < gridRows; r++) {
        for (let c = 0; c < gridCols; c++) {
          ctx.fillStyle = latentColor(grid[r][c]);
          ctx.fillRect(sx + c * cw, sy + r * ch, cw - 0.5, ch - 0.5);
        }
      }

      if (t % 5 === 0) {
        ctx.fillStyle = '#666';
        ctx.font = '8px monospace';
        ctx.textAlign = 'center';
        ctx.fillText('t=' + t, sx + cellW / 2, sy + cellH * gridRows + 12);
      }

      if (t < totalSteps - 1) {
        const arrowX = sx + cellW + 1;
        const arrowY = sy + (cellH * gridRows) / 2;
        ctx.strokeStyle = 'rgba(168,85,247,0.3)';
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(arrowX, arrowY);
        ctx.lineTo(arrowX + stepSpacing - cellW - 3, arrowY);
        ctx.stroke();
      }
    }

    // Gaussian mixture components
    const mixY = h - pad.bottom + 10;
    ctx.fillStyle = '#888';
    ctx.font = '9px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('MDN Mixture Components (5 Gaussians)', w / 2, mixY - 2);

    const mixColors = ['#ef4444', '#f59e0b', '#10b981', '#3b82f6', '#a855f7'];
    const mixRng = seededRandom(100);
    const componentWidth = availW / numMixtureComponents;
    const selectedComponent = Math.floor(tau * 2) % numMixtureComponents;

    for (let i = 0; i < numMixtureComponents; i++) {
      const cx = pad.left + i * componentWidth + componentWidth / 2;
      const cy = mixY + 22;
      const weight = 0.1 + mixRng() * 0.3;
      const radius = 8 + weight * 15;
      const sigma = (0.3 + mixRng() * 0.5) * tau;

      ctx.beginPath();
      ctx.arc(cx, cy, radius, 0, 2 * Math.PI);
      ctx.fillStyle = i === selectedComponent ? mixColors[i] : mixColors[i] + '40';
      ctx.fill();

      if (i === selectedComponent) {
        ctx.strokeStyle = '#fff';
        ctx.lineWidth = 2;
        ctx.stroke();

        ctx.beginPath();
        ctx.arc(cx, cy, radius + sigma * 10, 0, 2 * Math.PI);
        ctx.strokeStyle = mixColors[i] + '60';
        ctx.lineWidth = 1;
        ctx.setLineDash([3, 3]);
        ctx.stroke();
        ctx.setLineDash([]);
      }

      ctx.fillStyle = '#888';
      ctx.font = '8px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('\u03C0' + (i + 1), cx, cy + radius + 14);
    }

    ctx.fillStyle = mixColors[selectedComponent];
    ctx.font = '9px sans-serif';
    ctx.textAlign = 'right';
    ctx.fillText('\u03C0' + (selectedComponent + 1) + ' selected', w - pad.right, mixY + 50);
  }, [dreamSize, tau]);

  useEffect(() => {
    drawDreamRollout();
  }, [drawDreamRollout]);

  /* ---- Benchmark data for selected task ---- */
  const task = benchmarkData[selectedTask];

  /* ---- Render ---- */
  return (
    <div className="method-page">
      <h1>World Models</h1>
      <p className={styles.subtitle}>
        Recurrent World Models Facilitate Policy Evolution &mdash; Ha &amp; Schmidhuber, 2018
      </p>
      <div className={styles.paperLink}>
        <a href="https://worldmodels.github.io" target="_blank" rel="noopener noreferrer">
          <span className={styles.paperLinkIcon}>&rarr;</span> worldmodels.github.io
        </a>
      </div>

      <CoreIdeasAndFeatures coreIdeas={coreIdeas} keyFeatures={keyFeatures} />

      {/* ==================== Main Grid: Model Components + Architecture ==================== */}
      <div className={styles.mainGrid}>
        {/* Model Components */}
        <div className={styles.card}>
          <div className={styles.cardTitle}>
            Model Components (V-M-C)
          </div>
          <div className={styles.modelEquations}>
            {/* V Model (VAE) */}
            <div
              className={activeModelItem === 'vae' ? styles.modelItemActive : styles.modelItem}
              onClick={() => setActiveModelItem(activeModelItem === 'vae' ? null : 'vae')}
            >
              <h4 className={styles.modelItemHeader}>
                <span className={styles.modelDot} style={{ background: '#10b981' }} />
                V Model (VAE)
              </h4>
              <div className={styles.formula}>
                <MathJax>{'\\( z \\sim \\text{Encoder}(x) \\)'}</MathJax>
              </div>
              <p className={styles.modelItemDesc}>
                Convolutional encoder/decoder compresses 64&times;64 frames to latent z (32-dim
                for CarRacing, 64-dim for VizDoom)
              </p>
            </div>

            {/* M Model (MDN-RNN) */}
            <div
              className={activeModelItem === 'mdnrnn' ? styles.modelItemActive : styles.modelItem}
              onClick={() => setActiveModelItem(activeModelItem === 'mdnrnn' ? null : 'mdnrnn')}
            >
              <h4 className={styles.modelItemHeader}>
                <span className={styles.modelDot} style={{ background: '#3b82f6' }} />
                M Model (MDN-RNN)
              </h4>
              <div className={styles.formula}>
                <MathJax>
                  {'\\( P(z_{t+1}) = \\sum_{i} \\pi_i \\, \\mathcal{N}(\\mu_i, \\sigma_i) \\)'}
                </MathJax>
              </div>
              <p className={styles.modelItemDesc}>
                LSTM-256 + Mixture Density Network output. Predicts P(z<sub>t+1</sub> | a
                <sub>t</sub>, z<sub>t</sub>, h<sub>t</sub>) as mixture of K Gaussians.
                Temperature &tau; controls sampling.
              </p>
            </div>

            {/* C Model (Controller) */}
            <div
              className={
                activeModelItem === 'controller' ? styles.modelItemActive : styles.modelItem
              }
              onClick={() =>
                setActiveModelItem(activeModelItem === 'controller' ? null : 'controller')
              }
            >
              <h4 className={styles.modelItemHeader}>
                <span className={styles.modelDot} style={{ background: '#f59e0b' }} />
                C Model (Controller)
              </h4>
              <div className={styles.formula}>
                <MathJax>{'\\( a_t = W_c [z_t ; h_t] + b_c \\)'}</MathJax>
              </div>
              <p className={styles.modelItemDesc}>
                Single linear layer. Only 867 parameters (CarRacing). Optimized by CMA-ES, not
                gradients.
              </p>
            </div>

            {/* Dream Environment */}
            <div
              className={activeModelItem === 'dream' ? styles.modelItemActive : styles.modelItem}
              onClick={() => setActiveModelItem(activeModelItem === 'dream' ? null : 'dream')}
            >
              <h4 className={styles.modelItemHeader}>
                <span className={styles.modelDot} style={{ background: '#a855f7' }} />
                Dream Environment
              </h4>
              <div className={styles.formula}>
                <MathJax>
                  {'\\( z_{t+1} \\sim \\text{MDN-RNN}(a_t, z_t, h_t; \\tau) \\)'}
                </MathJax>
              </div>
              <p className={styles.modelItemDesc}>
                M replaces the real environment. Generates z<sub>t+1</sub> by sampling from MDN.
                &tau;&gt;1 makes dreams harder/more stochastic.
              </p>
            </div>
          </div>
        </div>

        {/* Architecture SVG */}
        <div className={styles.card}>
          <div className={styles.cardTitle}>
            V-M-C Architecture
          </div>
          <svg className={styles.pipelineSvg} viewBox="0 0 500 380">
            {/* Arrow Markers */}
            <defs>
              <marker id="arrowCyan" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
                <polygon points="0 0, 10 3.5, 0 7" fill="#00d9ff" />
              </marker>
              <marker id="arrowBlue" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
                <polygon points="0 0, 10 3.5, 0 7" fill="#3b82f6" />
              </marker>
              <marker id="arrowOrange" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
                <polygon points="0 0, 10 3.5, 0 7" fill="#f59e0b" />
              </marker>
              <marker id="arrowGreen" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
                <polygon points="0 0, 10 3.5, 0 7" fill="#10b981" />
              </marker>
              <marker id="arrowPurple" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
                <polygon points="0 0, 10 3.5, 0 7" fill="#a855f7" />
              </marker>
              <marker id="arrowGray" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
                <polygon points="0 0, 10 3.5, 0 7" fill="#888" />
              </marker>
            </defs>

            {/* Real Mode Pipeline */}
            <text x="250" y="18" textAnchor="middle" fill="#f59e0b" fontSize="11" fontWeight="bold">
              Real Environment Mode
            </text>

            {/* Observation Image */}
            <rect
              x="15" y="35" width="70" height="55" rx="8"
              fill="rgba(255,255,255,0.1)" stroke="#888" strokeWidth="1.5"
              className={activeComponent === 'obs' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'obs' ? null : 'obs')}
            />
            <text x="50" y="55" textAnchor="middle" fill="#888" fontSize="9" fontWeight="bold" pointerEvents="none">
              Image
            </text>
            <text x="50" y="68" textAnchor="middle" fill="#666" fontSize="8" pointerEvents="none">
              64x64 obs
            </text>

            {/* V (VAE) */}
            <rect
              x="115" y="35" width="80" height="55" rx="8"
              fill="rgba(16,185,129,0.3)" stroke="#10b981" strokeWidth="2"
              className={activeComponent === 'vmodel' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'vmodel' ? null : 'vmodel')}
            />
            <text x="155" y="55" textAnchor="middle" fill="#10b981" fontSize="10" fontWeight="bold" pointerEvents="none">
              V (VAE)
            </text>
            <text x="155" y="68" textAnchor="middle" fill="#888" fontSize="8" pointerEvents="none">
              Encoder
            </text>

            {/* Arrow Obs to V */}
            <path d="M 85 62 L 113 62" stroke="#10b981" strokeWidth="2" fill="none" markerEnd="url(#arrowGreen)" className={styles.flowArrow} />

            {/* z_t label */}
            <text x="218" y="52" fill="#10b981" fontSize="9" fontWeight="bold">
              z_t
            </text>

            {/* M (MDN-RNN) */}
            <rect
              x="235" y="35" width="100" height="55" rx="8"
              fill="rgba(59,130,246,0.3)" stroke="#3b82f6" strokeWidth="2"
              className={activeComponent === 'mmodel' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'mmodel' ? null : 'mmodel')}
            />
            <text x="285" y="52" textAnchor="middle" fill="#3b82f6" fontSize="10" fontWeight="bold" pointerEvents="none">
              M (MDN-RNN)
            </text>
            <text x="285" y="68" textAnchor="middle" fill="#888" fontSize="8" pointerEvents="none">
              LSTM-256
            </text>

            {/* Recurrent arrow on M */}
            <path d="M 335 50 Q 355 30 335 42" stroke="#3b82f6" strokeWidth="1.5" fill="none" markerEnd="url(#arrowBlue)" />
            <text x="352" y="38" fill="#3b82f6" fontSize="7">h_t</text>

            {/* Arrow V to M */}
            <path d="M 195 62 L 233 62" stroke="#3b82f6" strokeWidth="2" fill="none" markerEnd="url(#arrowBlue)" className={styles.flowArrow} />

            {/* P(z_t+1) label */}
            <text x="355" y="75" fill="#3b82f6" fontSize="8">
              P(z<tspan baselineShift="sub" fontSize="6">t+1</tspan>)
            </text>

            {/* C (Controller) */}
            <rect
              x="380" y="35" width="90" height="55" rx="8"
              fill="rgba(245,158,11,0.3)" stroke="#f59e0b" strokeWidth="2"
              className={activeComponent === 'cmodel' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'cmodel' ? null : 'cmodel')}
            />
            <text x="425" y="52" textAnchor="middle" fill="#f59e0b" fontSize="10" fontWeight="bold" pointerEvents="none">
              C (Controller)
            </text>
            <text x="425" y="68" textAnchor="middle" fill="#888" fontSize="8" pointerEvents="none">
              Linear, 867p
            </text>

            {/* Arrow M to C */}
            <path d="M 335 62 L 378 62" stroke="#f59e0b" strokeWidth="2" fill="none" markerEnd="url(#arrowOrange)" className={styles.flowArrow} />

            {/* Action output */}
            <text x="425" y="108" textAnchor="middle" fill="#f59e0b" fontSize="9" fontWeight="bold">
              a_t (action)
            </text>
            <path d="M 425 90 L 425 100" stroke="#f59e0b" strokeWidth="2" fill="none" markerEnd="url(#arrowOrange)" />

            {/* Feedback arrow */}
            <path d="M 400 108 Q 340 120 285 92" stroke="#888" strokeWidth="1.5" fill="none" markerEnd="url(#arrowGray)" strokeDasharray="4" />
            <text x="345" y="118" fill="#888" fontSize="7">feedback</text>

            {/* Divider */}
            <line x1="20" y1="145" x2="480" y2="145" stroke="rgba(255,255,255,0.15)" strokeWidth="1" strokeDasharray="6" />

            {/* Dream Mode */}
            <text x="250" y="168" textAnchor="middle" fill="#a855f7" fontSize="11" fontWeight="bold">
              Dream Mode (Training C inside M)
            </text>

            {/* Dashed dream boundary */}
            <rect
              x="60" y="180" width="380" height="90" rx="12"
              fill="rgba(168,85,247,0.08)" stroke="#a855f7" strokeWidth="2" strokeDasharray="6"
              className={activeComponent === 'dreamenv' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'dreamenv' ? null : 'dreamenv')}
            />
            <text x="250" y="195" textAnchor="middle" fill="#a855f7" fontSize="8" fontStyle="italic" pointerEvents="none">
              Hallucinated Environment
            </text>

            {/* M in Dream */}
            <rect
              x="90" y="210" width="100" height="45" rx="8"
              fill="rgba(59,130,246,0.3)" stroke="#3b82f6" strokeWidth="2"
              className={activeComponent === 'mmodel_dream' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'mmodel_dream' ? null : 'mmodel_dream')}
            />
            <text x="140" y="228" textAnchor="middle" fill="#3b82f6" fontSize="9" fontWeight="bold" pointerEvents="none">
              M (MDN-RNN)
            </text>
            <text x="140" y="243" textAnchor="middle" fill="#888" fontSize="8" pointerEvents="none">
              replaces env
            </text>

            {/* C in Dream */}
            <rect
              x="260" y="210" width="100" height="45" rx="8"
              fill="rgba(245,158,11,0.3)" stroke="#f59e0b" strokeWidth="2"
              className={activeComponent === 'cmodel_dream' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'cmodel_dream' ? null : 'cmodel_dream')}
            />
            <text x="310" y="228" textAnchor="middle" fill="#f59e0b" fontSize="9" fontWeight="bold" pointerEvents="none">
              C (Controller)
            </text>
            <text x="310" y="243" textAnchor="middle" fill="#888" fontSize="8" pointerEvents="none">
              CMA-ES
            </text>

            {/* Closed loop arrows */}
            <path d="M 190 225 L 258 225" stroke="#10b981" strokeWidth="2" fill="none" markerEnd="url(#arrowGreen)" className={styles.flowArrow} />
            <text x="224" y="220" fill="#10b981" fontSize="8">z_t, h_t</text>

            <path d="M 310 255 Q 310 275 225 275 Q 140 275 140 257" stroke="#f59e0b" strokeWidth="2" fill="none" markerEnd="url(#arrowOrange)" className={styles.flowArrow} />
            <text x="225" y="285" textAnchor="middle" fill="#f59e0b" fontSize="8">a_t</text>

            {/* V removed */}
            <text x="40" y="240" fill="#ef4444" fontSize="8" fontWeight="bold">V removed</text>
            <text x="40" y="252" fill="#888" fontSize="7">(no images)</text>

            {/* CMA-ES section */}
            <text x="250" y="315" textAnchor="middle" fill="#888" fontSize="10" fontWeight="bold">
              CMA-ES Optimization Loop
            </text>

            <rect
              x="40" y="325" width="120" height="35" rx="8"
              fill="rgba(16,185,129,0.15)" stroke="#10b981" strokeWidth="1.5"
              className={activeComponent === 'population' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'population' ? null : 'population')}
            />
            <text x="100" y="346" textAnchor="middle" fill="#10b981" fontSize="9" fontWeight="bold" pointerEvents="none">
              Population of C
            </text>

            <rect
              x="190" y="325" width="120" height="35" rx="8"
              fill="rgba(168,85,247,0.15)" stroke="#a855f7" strokeWidth="1.5"
              className={activeComponent === 'evaluate' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'evaluate' ? null : 'evaluate')}
            />
            <text x="250" y="346" textAnchor="middle" fill="#a855f7" fontSize="9" fontWeight="bold" pointerEvents="none">
              Evaluate in Dreams
            </text>

            <rect
              x="340" y="325" width="120" height="35" rx="8"
              fill="rgba(245,158,11,0.15)" stroke="#f59e0b" strokeWidth="1.5"
              className={activeComponent === 'evolve' ? styles.pipelineStageActive : styles.pipelineStage}
              onClick={() => setActiveComponent(activeComponent === 'evolve' ? null : 'evolve')}
            />
            <text x="400" y="346" textAnchor="middle" fill="#f59e0b" fontSize="9" fontWeight="bold" pointerEvents="none">
              Evolve &amp; Select
            </text>

            <path d="M 160 342 L 188 342" stroke="#888" strokeWidth="1.5" fill="none" markerEnd="url(#arrowGray)" />
            <path d="M 310 342 L 338 342" stroke="#888" strokeWidth="1.5" fill="none" markerEnd="url(#arrowGray)" />
          </svg>

          {activeComponent !== null && componentInfo[activeComponent] && (
            <div className={styles.infoPanel}>
              <h4>{componentInfo[activeComponent].title}</h4>
              <p>{componentInfo[activeComponent].desc}</p>
            </div>
          )}
        </div>
      </div>

      {/* ==================== Dream Rollout + Benchmark ==================== */}
      <div className={styles.mainGrid}>
        {/* Dream Rollout with Temperature */}
        <div className={styles.card}>
          <div className={styles.cardTitle}>
            Dream Rollout with Temperature
          </div>
          <div className={styles.sliderContainer}>
            <label>Temperature &tau;:</label>
            <input
              type="range"
              className={styles.slider}
              min={1}
              max={20}
              step={1}
              value={temperature}
              onChange={(e) => setTemperature(parseInt(e.target.value))}
            />
            <span className={styles.sliderValue}>{tau.toFixed(1)}</span>
          </div>
          <div className={styles.canvasContainer}>
            <canvas ref={dreamCanvasRef} className={styles.imaginationCanvas} />
          </div>
          <div className={styles.metricsRow}>
            <div className={styles.metric}>
              <div className={styles.metricValue} style={{ color: '#a855f7' }}>
                {tau.toFixed(1)}
              </div>
              <div className={styles.metricLabel}>Temperature &tau;</div>
            </div>
            <div className={styles.metric}>
              <div className={styles.metricValue} style={{ color: '#3b82f6' }}>
                {avgVariance}
              </div>
              <div className={styles.metricLabel}>Avg Variance</div>
            </div>
            <div className={styles.metric}>
              <div className={styles.metricValue} style={{ color: stabilityColor }}>
                {stability}
              </div>
              <div className={styles.metricLabel}>Dream Stability</div>
            </div>
          </div>
          <p className={styles.dreamCaption}>
            Higher temperature &tau; increases stochasticity in the MDN-RNN sampling, making dreams
            more chaotic and training harder.
          </p>
        </div>

        {/* Benchmark Results */}
        <div className={styles.card}>
          <div className={styles.cardTitle}>
            Benchmark Results
          </div>
          <div className={styles.comparisonContainer}>
            <div className={styles.sliderContainer} style={{ marginTop: 0 }}>
              <label style={{ minWidth: 60 }}>Task:</label>
              <select
                className={styles.taskSelect}
                value={selectedTask}
                onChange={(e) => setSelectedTask(e.target.value)}
              >
                <option value="carracing">CarRacing-v0</option>
                <option value="vizdoom">VizDoom Take Cover</option>
              </select>
            </div>
            <div>
              {Object.entries(task.data).map(([method, score]) => {
                const pct = (Math.max(score, 0) / task.maxVal) * 100;
                const color = methodColors[method] || '#888';
                const isWM = method.startsWith('World Models');
                return (
                  <div className={styles.comparisonRow} key={method}>
                    <span
                      className={styles.comparisonLabel}
                      style={{ color, fontWeight: isWM ? 700 : 400 }}
                    >
                      {method}
                    </span>
                    <div className={styles.comparisonBarTrack}>
                      <div
                        className={styles.comparisonBarFill}
                        style={{
                          width: `${pct}%`,
                          background: color,
                          opacity: isWM ? 1 : 0.7,
                        }}
                      />
                    </div>
                    <span className={styles.comparisonValue} style={{ color }}>
                      {score}
                    </span>
                  </div>
                );
              })}
            </div>
            <p className={styles.benchmarkNote}>{task.note}</p>
          </div>
        </div>
      </div>

      {/* ==================== Training Objectives ==================== */}
      <div className={styles.cardMb}>
        <div className={styles.cardTitle}>
          Training Objectives
        </div>
        <div className={styles.modelEquations}>
          {/* VAE Loss */}
          <div className={styles.modelItem}>
            <h4 className={styles.modelItemHeader}>
              <span className={styles.modelDot} style={{ background: '#10b981' }} />
              VAE Loss (V Model)
            </h4>
            <div className={styles.formula}>
              <MathJax>
                {
                  '$$\\mathcal{L}_{\\text{VAE}} = -\\mathbb{E}_{q(z|x)}[\\log p(x|z)] + \\text{KL}[q(z|x) \\,\\|\\, p(z)]$$'
                }
              </MathJax>
            </div>
            <p className={styles.modelItemDesc}>
              Reconstruction loss (pixel-level) plus KL divergence regularization to shape the
              latent space. Trained independently on collected frames.
            </p>
          </div>

          {/* MDN-RNN Loss */}
          <div className={styles.modelItem}>
            <h4 className={styles.modelItemHeader}>
              <span className={styles.modelDot} style={{ background: '#3b82f6' }} />
              MDN-RNN Loss (M Model)
            </h4>
            <div className={styles.formula}>
              <MathJax>
                {
                  '$$P(z_{t+1} | a_t, z_t, h_t) = \\sum_i \\pi_i \\, \\mathcal{N}(z; \\mu_i, \\sigma_i), \\quad \\mathcal{L}_{\\text{MDN}} = -\\log P(z_{t+1})$$'
                }
              </MathJax>
            </div>
            <p className={styles.modelItemDesc}>
              Negative log-likelihood of the next latent vector under the mixture of Gaussians
              predicted by the MDN. Trained on sequences of (z, a) pairs.
            </p>
          </div>

          {/* Controller Objective */}
          <div className={styles.modelItem}>
            <h4 className={styles.modelItemHeader}>
              <span className={styles.modelDot} style={{ background: '#f59e0b' }} />
              Controller Objective (CMA-ES)
            </h4>
            <div className={styles.formula}>
              <MathJax>
                {
                  '$$\\max \\; \\mathbb{E}\\left[\\sum_t r_t\\right] \\quad \\text{where} \\quad a_t = W_c [z_t ; h_t] + b_c$$'
                }
              </MathJax>
            </div>
            <p className={styles.modelItemDesc}>
              Maximize cumulative reward by evolving the weight matrix W<sub>c</sub> and bias b
              <sub>c</sub>. CMA-ES maintains a distribution over parameter vectors and updates
              the covariance matrix based on fitness evaluations.
            </p>
          </div>
        </div>
      </div>

      {/* ==================== Paper Lineage ==================== */}
      <div className={styles.cardMb}>
        <div className={styles.cardTitle}>
          Paper Lineage
        </div>
        <div className={styles.lineageGrid}>
          {/* Builds On */}
          <div>
            <h4 className={styles.lineageColumnTitle} style={{ color: '#f59e0b' }}>
              Builds On
            </h4>
            <div className={styles.lineageItems}>
              {[
                {
                  title: 'VAE',
                  desc: 'Kingma & Welling, 2014 \u2014 Variational Autoencoder provides the V model for compressing observations into a continuous latent space.',
                },
                {
                  title: 'MDN',
                  desc: 'Bishop, 1994 \u2014 Mixture Density Networks output a mixture of Gaussians, enabling multi-modal predictions in the M model.',
                },
                {
                  title: 'RNN Sequence Models',
                  desc: 'Graves, 2013 \u2014 Recurrent neural networks for sequence generation. The LSTM backbone used in the MDN-RNN memory module.',
                },
                {
                  title: 'CMA-ES',
                  desc: 'Hansen, 2001 \u2014 Covariance Matrix Adaptation Evolution Strategy replaces gradient-based RL for optimizing the small controller.',
                },
                {
                  title: 'Learning to Think',
                  desc: 'Schmidhuber, 1990\u20132015 \u2014 Early ideas on learning world models and using them for planning and dreaming in recurrent controllers.',
                },
              ].map((item) => (
                <div
                  key={item.title}
                  className={styles.lineageItem}
                  style={{ borderLeftColor: '#f59e0b' }}
                >
                  <div className={styles.lineageItemTitle}>{item.title}</div>
                  <div className={styles.lineageItemDesc}>{item.desc}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Built Upon By */}
          <div>
            <h4 className={styles.lineageColumnTitle} style={{ color: '#10b981' }}>
              Built Upon By
            </h4>
            <div className={styles.lineageItems}>
              {[
                {
                  title: 'PlaNet',
                  desc: 'Hafner et al., 2019 \u2014 Replaces VAE+MDN-RNN with RSSM and uses online planning (CEM) instead of evolution. First model-based method competitive on continuous control.',
                },
                {
                  title: 'Dreamer',
                  desc: 'Hafner et al., 2020 \u2014 Builds on PlaNet with an actor-critic in latent imagination, backpropagating gradients through learned dynamics.',
                },
                {
                  title: 'GameGAN',
                  desc: 'Kim et al., 2020 \u2014 Learns a generative model that can simulate entire game environments (Pac-Man) without a game engine, inspired by dream training.',
                },
                {
                  title: 'Dreaming Approaches in RL',
                  desc: 'Various, 2019\u2013present \u2014 The idea of training policies in hallucinated environments has become a core paradigm in model-based RL research.',
                },
              ].map((item) => (
                <div
                  key={item.title}
                  className={styles.lineageItem}
                  style={{ borderLeftColor: '#10b981' }}
                >
                  <div className={styles.lineageItemTitle}>{item.title}</div>
                  <div className={styles.lineageItemDesc}>{item.desc}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

    </div>
  );
}
